### ISSUE TITLE
Batches and Metrics not working?

### ISSUE THREAD

**Issue by aromka** [daison12006013/laravel-horizon-cluster#1]
Just trying this out and seems to work great with AWS serverless redis, which uses clusters. Great job on that!

Noticed that Metrics and Batches don't seem to work when you dig deeper into the stats - just keeps loading. Is there anything that need to be adjusted for that?

**Comment by daison12006013** [comment]
I have a recent fix for this in our production, I'll update this package asap.

**Comment by daison12006013** [comment]
Here's our metrics in test environment
![image](https://github.com/daison12006013/laravel-horizon-cluster/assets/4581415/5e684660-4c5e-4321-987b-a47888fafa48)
![image](https://github.com/daison12006013/laravel-horizon-cluster/assets/4581415/37e67d34-d366-438c-8d13-0797d3732157)
![image](https://github.com/daison12006013/laravel-horizon-cluster/assets/4581415/f7b1a671-93c3-4c39-be25-12b77d9c27a7)

Make sure to always follow this instruction https://laravel.com/docs/10.x/horizon#metrics

I can confirm that the batches isn't compatible.

**Comment by aromka** [comment]
Nevermind, this was our internal route setting that was causing the issue, all good now. Thanks for doing great job on this!

**Comment by daison12006013** [comment]
@aromka appreciated your testing, hopefully this package can reach out more devs that uses cluster based redis.
