### ISSUE TITLE
Struggle to get this working.

### ISSUE THREAD

**Issue by iBotPeaches** [daison12006013/laravel-horizon-cluster#10]
Cool package and thankful it existed, but it doesn't appear to work and since we fight so many battles getting Cluster support in Laravel. We are undoing the choice, but I wanted to leave the feedback I hit.

The documentation suggests doing `clusters.default`, which in my understanding is wrong. You can see in the [Horizon code](https://github.com/laravel/horizon/blob/5.x/src/Horizon.php#L103-L111). This is causing the search to fail, because its already compounding the `clusters.` onto the lookup.

So when you do `clusters.default` you make `database.redis.clusters.clusters.default.0` which is invalid, thus it finds nothing. So it copies the entry at `database.redis.clusters.default` which exists (but wrongly!) since you compounded the `clusters` key onto it.

So now we have an entry found, which Laravel thinks is a non-cluster, but its a cluster. So Horizon then copies that to make its own "horizon" config

```php
config(['database.redis.horizon' => $config]);
```

So now we have a cluster config (default) copied into the root (non-cluster) and treated as a non-cluster, but its a cluster. Thus you get a crash because you are sending cluster commands to the non-Cluster service.

```
RedisException MOVED 1205 172.18.0.10:6379
```

So best I can understand for anyone who got this to work - you are balancing both a Cluster and non-Cluster Redis service. Open for feedback if you spot anything wrong in this discovery.

Thanks.

**Comment by daison12006013** [comment]
Found it, it's predis Client class, another way is to use reflection, can you run this via tinker

```
use Illuminate\Support\Facades\Redis;
use ReflectionClass;

// Get the Redis client object
$redisClient = Redis::connection('horizon')->client();

// Use reflection to access the protected $options property
$reflection = new ReflectionClass($redisClient);
$optionsProperty = $reflection->getProperty('options');
$optionsProperty->setAccessible(true);
$options = $optionsProperty->getValue($redisClient);

// Print the options
print_r($options);
```

![image](https://github.com/user-attachments/assets/1739b6a8-975a-4395-b254-5792f9027b09)

**Comment by iBotPeaches** [comment]
Thanks - I'm getting lost in your explanation though. My discovered issue is my cluster connection is being copied (because I did `clusters.default`) into a non-cluster key `database.redis.horizon`.

Thus when this code runs

https://github.com/laravel/framework/blob/11.x/src/Illuminate/Redis/RedisManager.php#L109-L118
```php
        if (isset($this->config[$name])) {
            return $this->connector()->connect(
                $this->parseConnectionConfiguration($this->config[$name]),
                array_merge(Arr::except($options, 'parameters'), ['parameters' => Arr::get($options, 'parameters.'.$name, Arr::get($options, 'parameters', []))])
            );
        }

        if (isset($this->config['clusters'][$name])) {
            return $this->resolveCluster($name);
        }
```

My connection resolves as a non-cluster and fails. What am I missing with your explanation? I do use PHPRedis, so perhaps thats part of it.

**Comment by daison12006013** [comment]
@iBotPeaches can you provide the full repository, have you tried to set this up on a new laravel repo?

Can I check what's inside your `config/queue.php`, especially the redis part

**Comment by iBotPeaches** [comment]
@daison12006013 - apologies for stealing your time. I have no interest in running clusters or this at the moment, so I don't want to continue to steal your time. Thanks for help thus far - I'll close this out.
