### ISSUE TITLE
Laravel 11 support

### ISSUE THREAD

**Issue by aromka** [daison12006013/laravel-horizon-cluster#2]
Are you planning to add Laravel 11 support?

**Comment by daison12006013** [comment]
@aromka feel free to create a PR, I guess nothing much to update just the `illuminate/*`

**Comment by aromka** [comment]
Created PR here - https://github.com/daison12006013/laravel-horizon-cluster/pull/3 - seems to work.

**Comment by aromka** [comment]
@daison12006013 - can you tag the release so the laravel update can be pulled with composer?

**Comment by daison12006013** [comment]
Done @aromka
