### ISSUE TITLE
Jobs dispatched but always write errors on laravel.log

### ISSUE THREAD

**Issue by stephanesoares** [daison12006013/laravel-horizon-cluster#9]
[2024-09-26 10:52:46] local.ERROR: Cannot use 'EVAL' with redis-cluster. {"exception":"[object] (Predis\\NotSupportedException(code: 0): Cannot use 'EVAL' with redis-cluster. at /home/stephane/public_html/wms/vendor/predis/predis/src/Connection/Cluster/RedisCluster.php:354)
[stacktrace]
#0 /home/stephane/public_html/wms/vendor/predis/predis/src/Connection/Cluster/RedisCluster.php(523): Predis\\Connection\\Cluster\\RedisCluster->getConnectionByCommand()
#1 /home/stephane/public_html/wms/vendor/predis/predis/src/Connection/Cluster/RedisCluster.php(583): Predis\\Connection\\Cluster\\RedisCluster->retryCommandOnFailure()
#2 /home/stephane/public_html/wms/vendor/predis/predis/src/Client.php(381): Predis\\Connection\\Cluster\\RedisCluster->executeCommand()
#3 /home/stephane/public_html/wms/vendor/predis/predis/src/Client.php(335): Predis\\Client->executeCommand()
#4 /home/stephane/public_html/wms/vendor/laravel/framework/src/Illuminate/Redis/Connections/Connection.php(116): Predis\\Client->__call()
#5 /home/stephane/public_html/wms/vendor/laravel/framework/src/Illuminate/Redis/Connections/Connection.php(229): Illuminate\\Redis\\Connections\\Connection->command()
#6 /home/stephane/public_html/wms/vendor/daison/laravel-horizon-cluster/src/Mod/RedisMetricsRepository.php(99): Illuminate\\Redis\\Connections\\Connection->__call()
#7 /home/stephane/public_html/wms/vendor/laravel/horizon/src/Listeners/UpdateJobMetrics.php(52): Daison\\LaravelHorizonCluster\\Mod\\RedisMetricsRepository->incrementQueue()
#8 /home/stephane/public_html/wms/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(478): Laravel\\Horizon\\Listeners\\UpdateJobMetrics->handle()
#9 /home/stephane/public_html/wms/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(286): Illuminate\\Events\\Dispatcher->Illuminate\\Events\\{closure}()
#10 /home/stephane/public_html/wms/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(266): Illuminate\\Events\\Dispatcher->invokeListeners()
#11 /home/stephane/public_html/wms/vendor/vladimir-yuldashev/laravel-queue-rabbitmq/src/Horizon/RabbitMQQueue.php(108): Illuminate\\Events\\Dispatcher->dispatch()
#12 /home/stephane/public_html/wms/vendor/vladimir-yuldashev/laravel-queue-rabbitmq/src/Horizon/RabbitMQQueue.php(94): VladimirYuldashev\\LaravelQ

I have my queues at rabbitmq, im using horizon connected to redis cluster.

I install your package, add dont-discover, configurations at config/database.php and config/horizon.php

Its missing anything?

**Comment by daison12006013** [comment]
@stephanesoares what's your `config/queue.php` looks like especially the redis?

**Comment by stephanesoares** [comment]
i solve this usign a redis non-cluster only for horizon
